-- Generated by the database client.
CREATE TABLE islamic_library (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    pdf_name varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    storage_key varchar(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

-- Categories table
CREATE TABLE categories (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

-- Normalized library table
CREATE TABLE library (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    pdf_name varchar(255) NOT NULL,
    category_id integer NOT NULL,
    storage_key varchar(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

-- Insert unique categories from existing data
INSERT INTO
    categories (name)
SELECT DISTINCT
    category
FROM islamic_library
WHERE
    category IS NOT NULL;

-- Insert library records with category_id references
INSERT INTO
    library (
        name,
        pdf_name,
        category_id,
        storage_key,
        is_active
    )
SELECT il.name, il.pdf_name, c.id as category_id, il.storage_key, il.is_active
FROM
    islamic_library il
    JOIN categories c ON c.name = il.category;